# Site
repository: realmiketalbot/realmiketalbot.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mike Talbot
title: Water Resources Engineer
email: mtalbot@eorinc.com
website: https://www.eorinc.com/about/our-team/mike-talbot.html

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  realmiketalbot
linkedin_username: realmiketalbot

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Coming soon.