# Newest first
- title: Mentor, OURA Mentored and Matched Scholars
  date: Spring 2026
  url: https://tilt.colostate.edu/oura/mentored-scholars-matching-grants/
- title: Co-Chair, Hydrology Days Organizing Committee
  date: Spring 2026
  url: https://www.engr.colostate.edu/ce/events/hydrology-days/
- title: Peer Reviewer, Journal of Hydrology
  date: 2026 – Present
  url: https://www.sciencedirect.com/journal/journal-of-hydrology
- title: Peer Reviewer, Frontiers of Earth Science
  date: 2025 – Present
  url: https://link.springer.com/journal/11707
- title: Mentor, Scott Undergraduate Research Experience (SURE)
  date: Spring 2025
  url: https://www.engr.colostate.edu/walter-scott-jr-gift/sure/
- title: Treasurer, Environmental & Water Resources Institute (EWRI) Graduate Student Group
  date: "2025"
  url: https://www.engr.colostate.edu/organizations/ewri/
- title: Co-Chair, Water Engineering and Science (WES) Seminar
  date: Fall 2024
  url: https://www.engr.colostate.edu/ce/events/water-seminar/
